# Generated by Django 5.0.6 on 2024-06-25 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
